### ISSUE TITLE
Show a fancy loader on loading

### ISSUE THREAD

**Issue by kenji4569** [scubism/react_todo_web#1]
Replace `<div>Loading..</div>` in js/containers/TodoContainer.js by a fancy loader.

There are some candidate packages for the loader:

candidate1:
https://github.com/jonjaques/react-loaders

candidate2:
https://github.com/rackt/react-modal

candidate3:
http://shibe97.github.io/react-awesome-modal/

I think candidate1 would be better if no trouble.

**Comment by hnq90** [comment]
@kenji4569 Yes, I would try `react-loaders`.
The 2nd & 3rd one is using to create model, that's not match our need.

**Comment by kenji4569** [comment]
And also prevent actions during loading.

**Comment by kenji4569** [comment]
@hnq90 Could you put the loader at the center of loading component: TodoLayout. I think react-dimensions (https://www.npmjs.com/package/react-dimensions) could be useful.

**Comment by hnq90** [comment]
@kenji4569 Okay. I will try it.

**Comment by kenji4569** [comment]
@hnq90 Could you please put the loader with overlaid on a center of TodoContainer, using "position absolute" for the loader and "position relative" for the background container.

**Comment by hnq90** [comment]
@kenji4569 Ah, you meant we will display the loader as an overlay of TodoContainer (class ".todo-container")?

**Comment by hnq90** [comment]
@kenji4569 Like this image? (The loading text will be replaced by animation)
 ![overlay](https://cloud.githubusercontent.com/assets/1875666/11874444/4d697972-a512-11e5-8ab4-353bb00cdc31.png)

**Comment by kenji4569** [comment]
@hnq90 Yes, please.
