### ISSUE TITLE
Show errors by a modal dialog with fixing for non-JSON structured error response

### ISSUE THREAD

**Issue by kenji4569** [scubism/react_todo_web#2]
Replace `<div>{JSON.stringify(this.props.error)}</div>` in TodoContainer.js by a modal dialog. Show both JSON and non-JSON structured error responses properly.

Candidate packages are shown below in preference order:

candidate1:
https://github.com/fcomb/react-f-ui-modal

candidate2:
https://github.com/rackt/react-modal

candidate3:
http://shibe97.github.io/react-awesome-modal/

**Comment by kenji4569** [comment]
@hnq90 Could you do refactoring for error handling logic by placing it to fetchUtil.js

**Comment by kenji4569** [comment]
@hnq90 Add a close button (put button with text "x")  to the popup, and Fix the height of the popup with its content height.

**Comment by hnq90** [comment]
@kenji4569 

> Could you do refactoring for error handling logic by placing it to fetchUtil.js
> Add a close button (put button with text "x") to the popup, and Fix the height of the popup with its content height.

Okay, I got it.

**Comment by kenji4569** [comment]
@hnq90 Is the DayPicker displayed in inline format or popup format? Please display the picker in popup format.
