### ISSUE TITLE
Set due date to todo item

### ISSUE THREAD

**Issue by kenji4569** [scubism/react_todo_web#6]
Set due date to todo item
1. install a client library

candidate 1:
http://www.gpbl.org/react-day-picker/

candidate2: (too simple)
https://github.com/Hacker0x01/react-datepicker

candidate3: (less stars than candidate1)
http://zippyui.com/react-date-picker/
1. make a form and display due date if set

Put a small icon to open a calendar to set due date 
1. (server side) add due_date field to todo model and modify the API
2. Implement actions and reducers with API fetching

**Comment by kenji4569** [comment]
@hnq90 Fix the layout of TodoListItem which is now broken with due_date text.

**Comment by hnq90** [comment]
@kenji4569 Yes, I got it.

**Comment by kenji4569** [comment]
@hnq90 Is the DayPicker displayed in inline format or popup format? Please display the picker in popup format.

**Comment by kenji4569** [comment]
@hnq90 I merged. Almost ok, except that when you set empty due_date, the server returns a parse error, while the error dialog only show "Bad Request". Please fix the dialog problem, and also fix server side to accept empty the due_date. And should we use mongo timestamp for server side date filed or should we use integer for it as in Yii? (Do you have any reason to use mongo timestamp?)

**Comment by kenji4569** [comment]
@hnq90 And Is the DayPicker still displayed in an inline format?

**Comment by hnq90** [comment]
> I merged. Almost ok, except that when you set empty due_date, the server returns a parse error, while the error dialog only show "Bad Request". Please fix the dialog problem, and also fix server side to accept empty the due_date. And should we use mongo timestamp for server side date filed or should we use integer for it as in Yii? (Do you have any reason to use mongo timestamp?)

I think we should use unix timestamp format. I will change it.

> And Is the DayPicker still displayed in an inline format?

I'm finding a way which doesn't use other library. 

I will do it on tomorrow morning.

**Comment by kenji4569** [comment]
@hnq90 OK, thanks.

**Comment by kenji4569** [comment]
@hnq90 Please checkout the latest master of go_todo_api to fix the server side api.
